### ISSUE TITLE
Java errors from jsonio examples

### ISSUE THREAD

**Issue by ViscidKonrad** [wbuchanan/StataJavaUtilities#1]
```
. sysuse auto, clear
(1978 Automobile Data)

. jsonio out, what(record) obid(74)
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.stata.Javacall.load(Javacall.java:130)
        at com.stata.Javacall.load(Javacall.java:90)
Caused by: java.lang.NoSuchMethodError: org.paces.Stata.MetaData.Meta: method <init>()V not found
        at org.paces.Stata.JSON.StataJSON.printRecord(StataJSON.java:84)
        ... 6 more
r(5100);
```

**Comment by wbuchanan** [comment]
This is the wrong repository for the issue as best I can tell.  I am going to close this issue here, but you can find the reference to it [here](https://github.com/wbuchanan/StataJSON/issues/28) in the jsonio repository.
